[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://labflow-admin-backend-273b.onrender.com/api"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
